version: '3.0'

services:
  db:
    image: postgres:16
    # restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sync-focus-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.volume/postgresql:/var/lib/postgresql/data/

  # backend:
  #   build: ./backend
  #   ports:
  #     - 5001:5001
  #   volumes:
  #     - ./backend/:/usr/backend/
  #   env_file:
  #     - ./backend/production.env
  #   command: python3 run.py --prod
  #   restart: always
  #   depends_on:
  #     - db

  # open http://localhost:16686
  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
      - "4318:4318"
      - "4317:4317"

networks:
  default:
    name: sync_focus_network

