version: '3.0'

services:
  db:
    image: postgres:16
    # profiles: [backend-dev, production]
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sync-focus-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.volume/postgresql:/var/lib/postgresql/data/

  # backend:
  #   build: .
  #   profiles: [production]
  #   restart: unless-stopped
  #   ports:
  #     - 5001:5001
  #   volumes:
  #     - ./backend/:/usr/backend/
  #   # env_file:
  #     # - ./backend/production.env
  #   command: python3 run.py --prod
  #   depends_on:
  #     - db

  # open http://localhost:16686
  jaeger:
    image: jaegertracing/all-in-one
    # profiles: [backend-dev, production]
    restart: unless-stopped
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411

networks:
  default:
    name: sync_focus_network

