version: '1.0'

services:
  db:
    image: postgres:15.1
    env_file:
      - path: example.env
        required: false
      - path: .env
        required: false
    # restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: sync-focus-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./.volume/postgresql:/var/lib/postgresql/data/

  # backend:
  #   build: ./backend
  #   ports:
  #     - 5001:5001
  #   volumes:
  #     - ./backend/:/usr/backend/
  #   env_file:
  #     - ./backend/production.env
  #   command: python3 run.py --prod
  #   restart: always
  #   depends_on:
  #     - db

networks:
  default:
    name: sync_focus_network

